#!/bin/bash

git pull

packageVersion="$(grep -o '\"version\": \"[^\"]*' ./composer.json | grep -o '[^\"]*$')"
lastTagVersion="$(git tag --sort=committerdate | grep -E '[0-9]' | tail -1)"

if [ "$packageVersion" == "$lastTagVersion" ]; then
	echo "Package version has not been updated in composer.json file. Can't publish."
	exit;;
fi

read -p "New version will be $packageVersion (actual is $lastTagVersion). Confirm ? (y/n) " yn

case $yn in
  [yY] ) echo "Publishing  new version..."
    git tag $packageVersion
    git push origin $packageVersion
    exit;;
  * ) echo "Abort. Suggestion : increase the version number in composer.json and then retry."
    exit;;
esac


# json='{"access_token":"kjdshfsd", "key2":"value"}'

# echo $json | grep -o '"access_token":"[^"]*' | grep -o '[^"]*$'